### ISSUE TITLE
NVMe support

### ISSUE THREAD

**Issue by MarcusWichelmann** [hn/debian-stretch-zfs-root#10]
Good news, this script worked great for installing Debian on ZFS on two NVMe disks. Thank you very much!

Only thing that needs to be changed is the `lsblk` command to list NVMe drives:
```
lsblk -I259 -dn -o name
```

See:
https://github.com/hn/debian-stretch-zfs-root/blob/master/debian-stretch-zfs-root.sh#L47

**Comment by hn** [comment]
Thanks for reporting. NVMe support has been added in https://github.com/hn/debian-stretch-zfs-root/commit/7bdd5e399fbf6b696ab313f91b048a4e95fdbe79 (untested, hope it works ...)
