### ISSUE TITLE
Wanting /dev/disk-by-id to be used instead of /dev/sda

### ISSUE THREAD

**Issue by joebitcoinorg** [hn/debian-stretch-zfs-root#6]
Hello,
I use ProxMox.com which is a rebuild of Debian Stretch and offers a ZFS install option.
However the Zpools are created using /dev/sda  style designators.  

According to[ this](https://github.com/zfsonlinux/zfs/wiki/Debian-Stretch-Root-on-ZFS) 

> _Always` use the long /dev/disk/by-id/* aliases with ZFS. Using the /dev/sd* device nodes directly can cause sporadic import failures, especially on systems that have more than one storage pool._

So maybe this is the upstream location where this issue can be brought up?   

I see on the front page of this project that there is a sporatic bug in bringing up ZPools with more than 4 drives using the /dev/disk-by-id  method - hence I can see it would be a very good reason to temporarily use /dev/sda style identifiers.  
On the front page of the hn/debian-stretch-zfs-root page it reads:
_

> grub-install mysteriously fails for disk numbers >= 4 (grub-install: error: cannot find a GRUB drive for /dev/disk/by-id/...).

_

`

**Comment by hn** [comment]
My script does not pass any disks id's to grub (neither `/dev/disk-by-id/` nor `/dev/sd*`). I think the "`cannot find a GRUB drive for /dev/disk/by-id/`" error is related to the grub package and not to ZFS.

But that's just a guess ... I've never investigated further (and currently do not have time to do that). Feel free to contribute!

I've never had any problems with ZFS not finding "`/dev/disk/by-id/`" disks.
